export type ExerciseCategory = "superiores" | "inferiores";

export interface ExerciseGuideItem {
  id: string;
  nome: string;
  categoria: ExerciseCategory;
  grupo: string;
  musculos: string[];
  resumo: string;
  comoFazer: string[];
  posicao: string[];
  cuidados: string[];
  videoId?: string;
}

export const exerciseGuide: ExerciseGuideItem[] = [
  {
    id: "sissy-squat",
    nome: "Sissy Squat",
    categoria: "inferiores",
    grupo: "Quadríceps",
    musculos: ["Quadríceps", "Joelhos", "Equilíbrio"],
    resumo: "Agachamento de joelho com foco forte em quadríceps e controle corporal.",
    comoFazer: [
      "Fique em pé, eleve os calcanhares e mantenha o tronco inclinado para trás.",
      "Flexione os joelhos deixando-os avançarem sobre os pés.",
      "Desça até sentir forte tensão no quadríceps e retorne com controle.",
    ],
    posicao: [
      "Pés firmes e alinhados na largura do quadril.",
      "Tronco rígido, abdômen contraído e quadril estendido.",
      "Use apoio com as mãos se ainda não tiver equilíbrio.",
    ],
    cuidados: [
      "Evite se houver dor anterior no joelho.",
      "Não deixe o quadril dobrar como em um agachamento comum.",
      "Comece com amplitude curta e progrida aos poucos.",
    ],
    videoId: "pU7XbxvViIY",
  },
  {
    id: "cardio-na-escada",
    nome: "Cardio na Escada",
    categoria: "inferiores",
    grupo: "Cardio",
    musculos: ["Cardio", "Glúteos", "Posterior de coxa"],
    resumo: "Subida em escadas para condicionamento, força funcional e gasto calórico.",
    comoFazer: [
      "Suba os degraus de forma ritmada, preferencialmente de dois em dois se tiver controle.",
      "Desça com cadência normal e segura.",
      "Mantenha o corpo levemente inclinado e use os braços para ajudar no ritmo.",
    ],
    posicao: [
      "Pise com o pé inteiro no degrau.",
      "Joelho acompanha a linha do pé.",
      "Tronco firme, olhar à frente e respiração contínua.",
    ],
    cuidados: [
      "Evite correr na descida.",
      "Não use degraus molhados ou instáveis.",
      "Reduza velocidade se perder a técnica.",
    ],
    videoId: "t_CXSbeAuYI",
  },
  {
    id: "step-up",
    nome: "Step Up",
    categoria: "inferiores",
    grupo: "Unilateral",
    musculos: ["Glúteos", "Quadríceps", "Equilíbrio unilateral"],
    resumo: "Subida em banco ou step com foco em força unilateral de pernas.",
    comoFazer: [
      "Coloque um pé sobre o banco ou step.",
      "Empurre o calcanhar do pé de cima para subir.",
      "Desça lentamente com a perna oposta e repita.",
    ],
    posicao: [
      "Banco estável, altura compatível com seu controle.",
      "Pé inteiro apoiado na plataforma.",
      "Tronco ereto durante toda a subida.",
    ],
    cuidados: [
      "Não impulsione demais com a perna de baixo.",
      "Evite deixar o joelho cair para dentro.",
      "Controle a descida para proteger joelho e quadril.",
    ],
    videoId: "btF1VEFQG18",
  },
  {
    id: "glute-bridge",
    nome: "Glute Bridge",
    categoria: "inferiores",
    grupo: "Glúteos",
    musculos: ["Glúteos", "Posterior de coxa", "Core"],
    resumo: "Ponte de quadril no chão para ativar glúteos e estabilizar a pelve.",
    comoFazer: [
      "Deite de costas com joelhos dobrados e pés no chão.",
      "Empurre os calcanhares, contraia glúteos e eleve o quadril.",
      "Segure no topo e desça sem perder o controle.",
    ],
    posicao: [
      "Pés na largura do quadril.",
      "Costelas baixas e abdômen firme.",
      "Joelhos apontando para frente.",
    ],
    cuidados: [
      "Não hiperestenda a lombar no topo.",
      "Evite empurrar com a ponta dos pés.",
      "Mantenha a contração no glúteo, não na lombar.",
    ],
    videoId: "LORVjN2bg5o",
  },
  {
    id: "infra-barra",
    nome: "Infra Barra",
    categoria: "superiores",
    grupo: "Costas",
    musculos: ["Dorsal inferior", "Lombares", "Bíceps"],
    resumo: "Remada com barra para dorsal inferior, costas e controle escapular.",
    comoFazer: [
      "Incline o tronco à frente com coluna neutra.",
      "Puxe a barra em direção ao abdômen.",
      "Retraia as escápulas e controle a descida.",
    ],
    posicao: [
      "Pés firmes no chão e joelhos levemente flexionados.",
      "Pegada segura na barra.",
      "Coluna neutra e pescoço alinhado.",
    ],
    cuidados: [
      "Não arredonde a lombar.",
      "Evite puxar com impulso.",
      "Use carga que permita controlar a fase negativa.",
    ],
    videoId: "OKiou9UhBtk",
  },
  {
    id: "abdominal-corda",
    nome: "Abdominal Corda",
    categoria: "superiores",
    grupo: "Core",
    musculos: ["Reto abdominal", "Oblíquos", "Core"],
    resumo: "Flexão de tronco na polia alta com corda, focada em contração abdominal.",
    comoFazer: [
      "Segure a corda atrás da cabeça na polia alta.",
      "Flexione o tronco em direção aos joelhos.",
      "Contraia o abdômen e retorne com controle.",
    ],
    posicao: [
      "Joelhos apoiados ou base firme em pé.",
      "Quadril estável.",
      "Corda próxima à cabeça sem puxar o pescoço.",
    ],
    cuidados: [
      "Não transforme em puxada de braço.",
      "Evite compensar com quadril.",
      "Mantenha o pescoço neutro.",
    ],
    videoId: "zp6uK1aE1Lc",
  },
  {
    id: "hiit-com-halteres",
    nome: "HIIT com Halteres",
    categoria: "superiores",
    grupo: "Condicionamento",
    musculos: ["Full body", "Metabolismo", "Potência"],
    resumo: "Circuito intervalado com halteres para força, potência e gasto calórico.",
    comoFazer: [
      "Escolha exercícios como swing, clean, press ou agachamento com halteres.",
      "Execute blocos curtos de alta intensidade.",
      "Intercale pausas controladas para manter qualidade técnica.",
    ],
    posicao: [
      "Base firme e halteres próximos ao corpo.",
      "Abdômen contraído antes de cada repetição.",
      "Ombros encaixados durante movimentos acima da cabeça.",
    ],
    cuidados: [
      "Não sacrifique técnica por velocidade.",
      "Use carga moderada.",
      "Pare se houver tontura ou perda de coordenação.",
    ],
    videoId: "nkY862kB9lA",
  },
  {
    id: "full-body",
    nome: "Full Body",
    categoria: "superiores",
    grupo: "Corpo todo",
    musculos: ["Corpo todo", "Hipertrofia", "Funcional"],
    resumo: "Treino que trabalha grandes grupos musculares em uma sessão única.",
    comoFazer: [
      "Combine empurrar, puxar, agachar, dobrar quadril e core.",
      "Organize exercícios com volume moderado por grupo muscular.",
      "Priorize movimentos bem executados antes de aumentar carga.",
    ],
    posicao: [
      "Ajuste cada exercício ao equipamento disponível.",
      "Mantenha postura neutra em todos os padrões.",
      "Use descansos suficientes para preservar qualidade.",
    ],
    cuidados: [
      "Não coloque volume alto demais para todos os grupos no mesmo dia.",
      "Evite falha técnica em exercícios complexos.",
      "Controle a intensidade se treinar full body várias vezes na semana.",
    ],
    videoId: "poVyhtdQBTo",
  },
  {
    id: "full-body-metabolico",
    nome: "Full Body Metabólico",
    categoria: "superiores",
    grupo: "Metabólico",
    musculos: ["Cardio", "Força", "EPOC"],
    resumo: "Versão em circuito do full body, com pouco descanso e alta demanda cardiovascular.",
    comoFazer: [
      "Encadeie exercícios de corpo todo em circuito.",
      "Use pausas curtas entre movimentos.",
      "Mantenha ritmo alto sem perder técnica.",
    ],
    posicao: [
      "Organize os equipamentos antes de iniciar.",
      "Mantenha área livre para transições rápidas.",
      "Respire de forma constante durante o circuito.",
    ],
    cuidados: [
      "Reduza carga se a respiração impedir boa execução.",
      "Evite movimentos muito técnicos quando estiver fadigado.",
      "Hidrate-se e respeite sinais de exaustão.",
    ],
    videoId: "ZZFKc4NLmyg",
  },
  {
    id: "face-pull",
    nome: "Face Pull",
    categoria: "superiores",
    grupo: "Ombros",
    musculos: ["Deltóide posterior", "Trapézio", "Manguito rotador"],
    resumo: "Puxada na polia para saúde dos ombros, postura e estabilidade escapular.",
    comoFazer: [
      "Na polia, puxe a corda em direção ao rosto.",
      "Mantenha cotovelos altos e abertos.",
      "Retorne devagar sem perder o controle das escápulas.",
    ],
    posicao: [
      "Polia na altura do rosto.",
      "Base firme, tronco estável.",
      "Punhos neutros e ombros longe das orelhas.",
    ],
    cuidados: [
      "Não puxe com lombar ou impulso.",
      "Evite carga alta demais.",
      "Sinta o trabalho na parte posterior do ombro.",
    ],
    videoId: "IeOqdw9WI90",
  },
  {
    id: "hiit-20-forte-2-leve",
    nome: "HIIT 20s Forte + 2min Leve",
    categoria: "superiores",
    grupo: "Cardio",
    musculos: ["Cardio", "Resistência", "Emagrecimento"],
    resumo: "Protocolo intervalado com 20 segundos fortes e 2 minutos leves.",
    comoFazer: [
      "Faça 20 segundos em esforço alto.",
      "Recupere por 2 minutos em ritmo leve.",
      "Repita os ciclos conforme o treino prescrito.",
    ],
    posicao: [
      "Use bike, esteira, escada, remo ou exercício seguro.",
      "Mantenha postura estável no equipamento escolhido.",
      "Controle a respiração na recuperação.",
    ],
    cuidados: [
      "Ideal para iniciar no intervalado sem exagero.",
      "Não comece no esforço máximo se não estiver aquecido.",
      "Pare em caso de dor no peito, tontura ou falta de ar fora do normal.",
    ],
    videoId: "7dzUGZdZrDw",
  },
  {
    id: "hiit-20-leve-20-forte",
    nome: "HIIT 20s Leve + 20s Forte",
    categoria: "superiores",
    grupo: "Cardio",
    musculos: ["Cardio", "VO2 máx", "Resistência"],
    resumo: "Protocolo alternado de 20 segundos leves com 20 segundos fortes.",
    comoFazer: [
      "Alterne 20 segundos em ritmo leve e 20 segundos em ritmo forte.",
      "Mantenha cadência clara entre os blocos.",
      "Repita até completar o tempo total planejado.",
    ],
    posicao: [
      "Escolha modalidade que permita troca rápida de intensidade.",
      "Postura firme e olhar à frente.",
      "Respiração ativa em todo o bloco.",
    ],
    cuidados: [
      "Exige melhor recuperação cardiovascular.",
      "Não deixe a técnica quebrar nos blocos fortes.",
      "Ajuste a intensidade antes de aumentar o volume.",
    ],
    videoId: "7dzUGZdZrDw",
  },
  {
    id: "hiit-4-forte-2-leve",
    nome: "HIIT 4min Forte + 2min Leve",
    categoria: "superiores",
    grupo: "Cardio avançado",
    musculos: ["Alta intensidade", "Condicionamento", "Endurance"],
    resumo: "Blocos longos de esforço elevado com recuperação ativa.",
    comoFazer: [
      "Execute 4 minutos em intensidade forte e sustentável.",
      "Recupere por 2 minutos em ritmo leve.",
      "Repita os blocos conforme condicionamento.",
    ],
    posicao: [
      "Use equipamento com controle de velocidade ou carga.",
      "Mantenha postura eficiente.",
      "Respire em ritmo constante para sustentar o bloco.",
    ],
    cuidados: [
      "Protocolo avançado: use com progressão.",
      "Não faça se estiver sem recuperação adequada.",
      "Reduza a intensidade se o esforço virar sprint descontrolado.",
    ],
    videoId: "7dzUGZdZrDw",
  },
  {
    id: "panturrilha-3-em-1",
    nome: "Panturrilha 3 em 1",
    categoria: "inferiores",
    grupo: "Panturrilhas",
    musculos: ["Gastrocnêmio", "Sóleo", "Tornozelo"],
    resumo: "Combinação de três posições de pés para trabalhar a panturrilha por completo.",
    comoFazer: [
      "Execute elevação de panturrilha com pés paralelos.",
      "Repita com pontas dos pés para fora.",
      "Finalize com pontas dos pés para dentro.",
    ],
    posicao: [
      "Apoie a ponta dos pés em superfície estável.",
      "Mantenha joelhos alinhados.",
      "Use amplitude máxima sem perder controle.",
    ],
    cuidados: [
      "Não quique no final do movimento.",
      "Controle a descida.",
      "Evite rotação exagerada dos joelhos.",
    ],
    videoId: "EILF4iyBxSQ",
  },
  {
    id: "hip-thrust",
    nome: "Hip Thrust",
    categoria: "inferiores",
    grupo: "Glúteos",
    musculos: ["Glúteo máximo", "Posterior de coxa", "Core"],
    resumo: "Elevação de quadril com costas apoiadas para máxima ativação de glúteos.",
    comoFazer: [
      "Apoie as costas no banco e posicione barra ou halter no quadril.",
      "Empurre o quadril para cima contraindo glúteos.",
      "Desça com controle mantendo a tensão.",
    ],
    posicao: [
      "Pés na largura dos ombros.",
      "Joelhos próximos de 90 graus no topo.",
      "Queixo levemente recolhido e costelas baixas.",
    ],
    cuidados: [
      "Não hiperestenda a lombar.",
      "Use proteção na barra se necessário.",
      "Evite deixar joelhos caírem para dentro.",
    ],
    videoId: "_i6qpcI1Nw4",
  },
  {
    id: "circuito-4-voltas",
    nome: "Circuito 4 Voltas",
    categoria: "superiores",
    grupo: "Condicionamento",
    musculos: ["Força", "Cardio", "Mobilidade"],
    resumo: "Sequência de exercícios executados um após o outro com pausa mínima.",
    comoFazer: [
      "Escolha a sequência definida no treino.",
      "Complete todos os exercícios da volta.",
      "Repita até fechar quatro voltas.",
    ],
    posicao: [
      "Organize estação e equipamentos antes de iniciar.",
      "Mantenha espaço seguro para transições.",
      "Controle respiração entre exercícios.",
    ],
    cuidados: [
      "Não transforme o circuito em corrida sem técnica.",
      "Ajuste cargas para conseguir completar as voltas.",
      "Descanse se a execução ficar insegura.",
    ],
    videoId: "dta3aMVe9qA",
  },
  {
    id: "terra-romeno",
    nome: "Terra Romeno",
    categoria: "inferiores",
    grupo: "Posterior",
    musculos: ["Posterior de coxa", "Glúteos", "Lombar"],
    resumo: "Dobradiça de quadril com foco em posterior de coxa e glúteos.",
    comoFazer: [
      "Segure a barra ou halteres à frente do corpo.",
      "Empurre o quadril para trás com joelhos levemente flexionados.",
      "Sinta alongar posterior de coxa e suba contraindo glúteos.",
    ],
    posicao: [
      "Coluna neutra e peito aberto.",
      "Peso próximo às pernas.",
      "Pés firmes e quadril indo para trás.",
    ],
    cuidados: [
      "Não arredonde as costas.",
      "Não transforme em agachamento.",
      "Pare a descida antes de perder a posição da coluna.",
    ],
    videoId: "p7X25bL7V-0",
  },
  {
    id: "respiracao-360-transverso",
    nome: "Respiração 360° + Ativação Transverso",
    categoria: "superiores",
    grupo: "Core profundo",
    musculos: ["Transverso abdominal", "Respiração", "Postura"],
    resumo: "Ativação terapêutica do core profundo com expansão do tronco em 360 graus.",
    comoFazer: [
      "Inspire expandindo costelas, abdômen e laterais do tronco.",
      "Expire contraindo suavemente o transverso abdominal.",
      "Pense em puxar o umbigo para dentro sem prender a respiração.",
    ],
    posicao: [
      "Deitado, sentado ou em quatro apoios.",
      "Coluna neutra.",
      "Ombros relaxados e mandíbula solta.",
    ],
    cuidados: [
      "Não faça força máxima no abdômen.",
      "Evite prender o ar.",
      "Use como preparação antes de treinos de core.",
    ],
    videoId: "Q85EzsgleaE",
  },
  {
    id: "elevacao-quadril-isometrica",
    nome: "Elevação de Quadril Isométrica",
    categoria: "inferiores",
    grupo: "Glúteos",
    musculos: ["Glúteos", "Estabilização pélvica", "Isometria"],
    resumo: "Ponte de quadril sustentada para ativação de glúteos e estabilidade.",
    comoFazer: [
      "Deite de costas e eleve o quadril até a posição de ponte.",
      "Contraia glúteos e mantenha a posição pelo tempo prescrito.",
      "Desça lentamente ao terminar.",
    ],
    posicao: [
      "Pés firmes no chão.",
      "Joelhos alinhados ao quadril.",
      "Costelas baixas e abdômen ativo.",
    ],
    cuidados: [
      "Não deixe a lombar dominar o movimento.",
      "Evite prender a respiração.",
      "Interrompa se sentir câimbra intensa.",
    ],
    videoId: "Y7EMWZNmvwA",
  },
  {
    id: "prancha-modificada-joelhos",
    nome: "Prancha Modificada - Joelhos",
    categoria: "superiores",
    grupo: "Core",
    musculos: ["Core", "Estabilização", "Transverso abdominal"],
    resumo: "Prancha com joelhos apoiados para desenvolver controle inicial do core.",
    comoFazer: [
      "Apoie antebraços e joelhos no chão.",
      "Mantenha o corpo alinhado dos joelhos à cabeça.",
      "Contraia abdômen e glúteos pelo tempo definido.",
    ],
    posicao: [
      "Cotovelos abaixo dos ombros.",
      "Pescoço neutro.",
      "Quadril alinhado, sem cair ou subir demais.",
    ],
    cuidados: [
      "Não prenda a respiração.",
      "Não deixe lombar afundar.",
      "Progrida para prancha completa somente com boa técnica.",
    ],
    videoId: "7EtpXXdxPMc",
  },
  {
    id: "pallof-press",
    nome: "Pallof Press",
    categoria: "superiores",
    grupo: "Core anti-rotação",
    musculos: ["Core anti-rotação", "Oblíquos", "Estabilidade"],
    resumo: "Empurrada horizontal resistindo à rotação do tronco.",
    comoFazer: [
      "Fique de lado para a polia ou elástico.",
      "Segure a alça no peito e empurre os braços à frente.",
      "Resista à rotação e retorne ao peito.",
    ],
    posicao: [
      "Base firme e joelhos levemente flexionados.",
      "Quadril e ombros apontados para frente.",
      "Abdômen contraído durante todo o movimento.",
    ],
    cuidados: [
      "Não gire junto com o cabo.",
      "Evite carga que puxe seu tronco para o lado.",
      "Faça ambos os lados.",
    ],
    videoId: "o8RNzx9WiNA",
  },
  {
    id: "vacuum-abdominal",
    nome: "Vacuum Abdominal",
    categoria: "superiores",
    grupo: "Core profundo",
    musculos: ["Transverso abdominal", "Core profundo", "Postura"],
    resumo: "Contração profunda do abdômen para ativar transverso e controle postural.",
    comoFazer: [
      "Esvazie os pulmões com uma expiração controlada.",
      "Puxe o abdômen para dentro e para cima.",
      "Segure pelo tempo definido e relaxe com controle.",
    ],
    posicao: [
      "Pode ser feito em pé, sentado, deitado ou em quatro apoios.",
      "Coluna neutra.",
      "Ombros relaxados.",
    ],
    cuidados: [
      "Não force até sentir dor ou tontura.",
      "Evite prender o ar por tempo excessivo.",
      "Faça longe de refeições pesadas.",
    ],
    videoId: "wT4DjGCFmXU",
  },
  {
    id: "agachamento-spanish-squat",
    nome: "Agachamento Spanish Squat",
    categoria: "inferiores",
    grupo: "Quadríceps",
    musculos: ["Quadríceps", "Joelho", "Reabilitação funcional"],
    resumo: "Agachamento com faixa fixa atrás dos joelhos, mantendo a tíbia mais vertical.",
    comoFazer: [
      "Prenda uma faixa elástica firme na altura dos joelhos.",
      "Passe a faixa atrás dos joelhos e incline o corpo para trás.",
      "Agache mantendo tensão na faixa e volte contraindo quadríceps.",
    ],
    posicao: [
      "Pés na largura do quadril.",
      "Tronco alto e abdômen firme.",
      "Tíbias próximas da vertical.",
    ],
    cuidados: [
      "Use ponto de fixação seguro.",
      "Não deixe os joelhos colapsarem para dentro.",
      "Comece sem carga externa.",
    ],
    videoId: "PBTChAcDnZ4",
  },
  {
    id: "abdominal-infra-suspenso",
    nome: "Abdominal Infra Suspenso",
    categoria: "superiores",
    grupo: "Core",
    musculos: ["Reto abdominal inferior", "Flexores do quadril", "Core"],
    resumo: "Elevação de joelhos ou pernas suspenso para abdômen inferior.",
    comoFazer: [
      "Fique suspenso em barras paralelas, barra fixa ou argolas.",
      "Contraia o abdômen e eleve joelhos ou pernas em direção ao peito.",
      "Desça sem balançar o corpo.",
    ],
    posicao: [
      "Pegada firme e ombros ativos.",
      "Pelve levemente encaixada.",
      "Movimento controlado, sem impulso.",
    ],
    cuidados: [
      "Evite balançar para subir as pernas.",
      "Não force a lombar.",
      "Comece com joelhos flexionados antes das pernas estendidas.",
    ],
    videoId: "pWGhRO5grqs",
  },
  {
    id: "prancha-lateral",
    nome: "Prancha Lateral",
    categoria: "superiores",
    grupo: "Core lateral",
    musculos: ["Oblíquos", "Core lateral", "Quadrado lombar"],
    resumo: "Isometria lateral para oblíquos, quadrado lombar e estabilidade do tronco.",
    comoFazer: [
      "Apoie o antebraço no chão e alinhe o corpo lateralmente.",
      "Eleve o quadril até formar uma linha reta.",
      "Contraia oblíquos e glúteos pelo tempo prescrito.",
    ],
    posicao: [
      "Cotovelo abaixo do ombro.",
      "Pés empilhados ou um à frente do outro.",
      "Cabeça alinhada ao tronco.",
    ],
    cuidados: [
      "Não deixe o quadril cair.",
      "Evite rodar o tronco para frente.",
      "Faça os dois lados com o mesmo controle.",
    ],
    videoId: "1Qo5djpn0pk",
  },
  {
    id: "infra-banco",
    nome: "Infra Banco",
    categoria: "superiores",
    grupo: "Core",
    musculos: ["Reto abdominal inferior", "Core", "Flexores do quadril"],
    resumo: "Elevação de pernas no banco para abdômen inferior com tensão constante.",
    comoFazer: [
      "Deite em banco plano ou inclinado e segure firme nas laterais.",
      "Eleve as pernas até perto de 90 graus com controle.",
      "Desça sem encostar os pés no chão para manter tensão no abdômen.",
    ],
    posicao: [
      "Lombar apoiada no banco.",
      "Pernas juntas ou levemente afastadas.",
      "Abdômen contraído antes de iniciar a descida.",
    ],
    cuidados: [
      "Não balance as pernas.",
      "Reduza amplitude se a lombar arquear.",
      "Dobre os joelhos se a versão com pernas estendidas ficar pesada.",
    ],
  },
];
